name: CI

on: [pull_request]

jobs:
  call-external:
    strategy:
      matrix:
        platform: [arm64, amd64]
      fail-fast: false
    uses: jina-ai/workflows-executors/.github/workflows/ci.yml@platform-aware
    with:
        platform: ${{ matrix.platform }}